####
#Classpath and file-based solution
####

server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          searchLocations: classpath:config/,classpath:config/account-service,classpath:config/customer-service
  profiles:
    active: native
  
       
